server:
  port: 8765
zuul:
  ignoredService: '*'
  routes:
    WeatherService:
      path: /weather/**
    DestinationService:
      path: /destination/**
    ReviewService:
      path: /review/**
    CompositeService:
      path: /composite/**
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5